feat: Add support for configuring wasmCloud Secrets
wasmCloud/wasmcloud-operator pull request #82
Opened 2024-07-26 20:01 UTC by joonas

## Feature or Problem

Since the features support is rolling out in the wasmCloud host, we should also add support to use it in the operator.

## Related Issues

## Release Information

## Consumer Impact

## Testing

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2024-07-26 20:03 UTC, ricochet approved these changes

2024-07-26 20:20 UTC, lxfontes requested changes
small doc nit

2024-07-26 20:20 UTC, lxfontes commented on examples/full-config/wasmcloud-annotated.yaml
> +  secrets_topic_prefix: "wasmcloud.secrets"
add `Optional/Required:` + decription to the key

2024-07-26 20:29 UTC, protochron approved these changes

2024-07-29 15:42 UTC, lxfontes approved these changes

2024-07-31 16:37 UTC, lxfontes commented on examples/full-config/wasmcloud-annotated.yaml
> +  secrets_topic_prefix: "wasmcloud.secrets"
heads up this will actually be `secretsTopicPrefix` due to camel-casing in the struct.

2024-07-31 19:48 UTC, joonas commented
Holding off merging this until we can change the `wadm-*` pins to point to non `-beta` versions of the published crates.

2024-08-01 17:13 UTC, merged